<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:if test="${empty productos}"><jsp:forward page="/SvCarrito" /></c:if>
<c:set var="titulo" value="Carrito de compras" /><c:set var="seccion" value="carrito" />
<%@ include file="WEB-INF/jspf/header.jspf" %>
<div class="page-heading"><span class="eyebrow">EJERCICIO 02</span><h1>Tu carrito de compras</h1><p class="text-secondary">Tecnología para tu espacio de trabajo. Revisa el detalle de los productos de ejemplo.</p></div>
<div class="row g-4"><div class="col-lg-9"><section class="card p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h4 mb-0">Detalle de productos</h2><span class="badge text-bg-light">${unidades} unidades</span></div><div class="table-responsive"><table class="table table-striped table-hover align-middle"><caption>Importes expresados en soles peruanos (PEN).</caption><thead><tr><th scope="col">ID</th><th scope="col">Producto</th><th scope="col" class="text-end">Precio</th><th scope="col" class="text-center">Cantidad</th><th scope="col" class="text-end">Subtotal</th></tr></thead><tbody>
<c:forEach items="${productos}" var="p"><tr><td class="text-secondary">0${p.id}</td><th scope="row"><c:out value="${p.nombre}" /></th><td class="text-end text-nowrap">S/ <fmt:formatNumber value="${p.precio}" minFractionDigits="2" maxFractionDigits="2" /></td><td class="text-center">${p.cantidad}</td><td class="text-end text-nowrap fw-semibold">S/ <fmt:formatNumber value="${p.subtotal}" minFractionDigits="2" maxFractionDigits="2" /></td></tr></c:forEach>
</tbody><tfoot><tr><th colspan="4" scope="row">Total general</th><td class="text-end text-nowrap fw-bold">S/ <fmt:formatNumber value="${total}" minFractionDigits="2" maxFractionDigits="2" /></td></tr></tfoot></table></div></section></div>
<aside class="col-lg-3"><div class="info-card"><span class="eyebrow">RESUMEN</span><h2 class="h5 mt-3">Total del carrito</h2><div class="cart-total">S/ <fmt:formatNumber value="${total}" minFractionDigits="2" maxFractionDigits="2" /></div><hr><p class="text-secondary small mb-0">4 productos diferentes<br>${unidades} unidades en total<br>Subtotal = precio × cantidad</p></div></aside></div>
<%@ include file="WEB-INF/jspf/footer.jspf" %>
